import { useState } from 'react';
import { ChevronDown } from 'lucide-react';
import { Link } from '@inertiajs/react';
import type { PayrollItem } from './types';
import { formatDate, getDailyRate, num, peso, totalDeductions, totalEarnings } from './payrollRunUtils';

const formatTime = (value: string | null) => value ? new Date(value).toLocaleTimeString('en-PH', { hour: 'numeric', minute: '2-digit' }) : '—';
const worked = (a: string | null, b: string | null) => { if (!a || !b) return 0; const x = new Date(a).getTime(), y = new Date(b).getTime(); return Number.isFinite(x) && Number.isFinite(y) && y > x ? Math.round((y - x) / 60000) : 0; };

export function PayrollItemMobileCard({ item, leavePayEnabled }: { item: PayrollItem; leavePayEnabled: boolean }) {
    const [expanded, setExpanded] = useState(false);
    const details = item.schedule_details ?? [];
    const employeeNumber = item.employee?.employee_id ?? item.employee_id;
    return <div className="overflow-hidden rounded-lg border bg-card">
        <button type="button" className="flex w-full items-center justify-between gap-3 p-4 text-left" onClick={() => setExpanded(v => !v)} aria-expanded={expanded}>
            <div className="min-w-0"><p className="truncate text-sm font-semibold">{item.employee?.full_name ?? employeeNumber}</p><p className="mt-1 text-xs text-muted-foreground">ID {employeeNumber} · {item.present_days} day(s) · {details.filter(d => d.actual_in && d.actual_out).length}/{details.length} duty(s) present</p></div>
            <div className="flex shrink-0 items-center gap-3"><div className="text-right"><p className="text-sm font-semibold text-primary">{peso(item.net_pay)}</p><p className="text-[11px] text-muted-foreground">Net pay</p></div><ChevronDown className={`h-4 w-4 transition-transform ${expanded ? 'rotate-180' : ''}`} /></div>
        </button>
        {expanded && <div className="border-t bg-muted/20 p-4"><div className="rounded-md border bg-background p-3"><div className="flex items-center justify-between"><p className="text-xs font-semibold">Scheduled vs actual</p><span className="text-[11px] text-muted-foreground">{item.present_days} present day(s)</span></div><div className="mt-3 space-y-2">
            {details.map(d => { const mins = worked(d.actual_in, d.actual_out); const start = d.scheduled_start.slice(11, 16), end = d.scheduled_end.slice(11, 16); return <div key={`${d.work_date}-${d.segment_no}`} className="rounded-md border p-2.5 text-xs"><div className="flex items-center justify-between gap-2 font-medium"><span>{formatDate(d.work_date)} · Duty {d.segment_no}</span><span>{num(Number(d.scheduled_minutes) / 60)}h scheduled</span></div><div className="mt-1 text-muted-foreground">Schedule: {start} – {end}{end <= start ? ' · Overnight' : ''}</div><div className="text-muted-foreground">Actual: {formatTime(d.actual_in)} – {formatTime(d.actual_out)}</div><div className="mt-1 text-muted-foreground">Worked: {num(mins / 60)}h ({mins} min)</div><div className="mt-2 grid grid-cols-2 gap-1.5"><span>Late: {d.late_minutes}m</span><span>Undertime: {d.undertime_minutes}m</span><span>OT: {d.overtime_minutes}m</span><span>Night diff: {d.night_diff_minutes}m</span></div></div> })}
            {!details.length && <p className="text-xs text-muted-foreground">No scheduled attendance records found for this employee.</p>}
        </div></div><div className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3 text-xs"><div><p className="text-muted-foreground">Employee ID</p><p className="font-medium">{employeeNumber}</p></div><div><p className="text-muted-foreground">Daily rate</p><p className="font-medium">{getDailyRate(item) ? peso(getDailyRate(item)) : '—'}</p></div><div><p className="text-muted-foreground">Basic pay</p><p className="font-medium">{peso(item.basic_pay)}</p></div><div><p className="text-muted-foreground">Overtime</p><p className="font-medium">{peso(item.overtime_pay)}</p></div><div><p className="text-muted-foreground">Holiday pay</p><p className="font-medium">{peso(item.holiday_pay)}</p></div><div><p className="text-muted-foreground">Night shift</p><p className="font-medium">{peso(item.night_diff)}</p></div><div><p className="text-muted-foreground">Leave pay</p><p className="font-medium">{leavePayEnabled ? peso(item.leave_pay) : 'Disabled'}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 rounded-md border bg-background p-3 text-xs"><div>Late <b>{item.late_minutes} min</b></div><div>Undertime <b>{item.undertime_minutes} min</b></div><div>Overtime <b>{item.overtime_minutes} min</b></div><div>Night diff <b>{item.night_diff_minutes} min</b></div><div>Paid days <b>{item.paid_leave_days ?? 0}</b></div><div>Absent days <b>{item.absent_days}</b></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-md border p-3"><p className="text-muted-foreground">Total earnings</p><p className="font-semibold">{peso(totalEarnings(item))}</p></div><div className="rounded-md border p-3"><p className="text-muted-foreground">Total deductions</p><p className="font-semibold">{peso(totalDeductions(item))}</p></div></div><Link href={`/employees/${item.employee?.id}/attendance`} target="_blank" className="mt-4 inline-block text-xs font-medium underline">View attendance details</Link></div>}
    </div>;
}
